### ISSUE TITLE
No module named `crgeo`

### ISSUE THREAD

**Issue by muety** [CommonRoad/crgeo#4]
I tried to install CommonRoad Geometric via pip as stated on the website (`pip install crgeo`), but am getting the following when trying to load a dataset.

```python
import torch
torch.load('data-0032-0000.pt')
```

**Error:**
```
ModuleNotFoundError: No module named 'commonroad_geometric.dataset'
```

I also tried to clone the repo and then run a `pip install .`. Apparently the package is named `commonroad_geometric` instead of `crgeo` then, but I'm still getting an error.

```python
from commonroad_geometric.dataset.commonroad_dataset import CommonRoadDataset
```

**Error:**
```
ModuleNotFoundError: No module named 'commonroad_geometric.dataset'
```

Also, the module seems to be empty:

```python
dir(commonroad_geometric)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']
```

**Comment by EiriniKot** [comment]
Hey!
Unfortunately, we were facing some issues with setup, but in the current release (version 0.1.2), import is fixed!

**Comment by EiriniKot** [comment]
Hey!
 Unfortunately, we were facing some issues with setup, but in the current release (version 0.1.2), import is fixed!
